---
- hosts: 127.0.0.1
  vars:
    user: padawan
    password: $1$SomeSalt$nUpHpwvl1J8CV0S8IvocE/
    group: coursera
  user: root
  tasks:
  - apt: upgrade=dist
  - apt: pkg=xauth state=installed
#We allow X11 forwarding
  - copy: dest=/root/.Xauthority content="" owner=root group=root mode=0600
  - group: name={{group}} state=present
  - user: name={{user}} password={{password}} createhome=yes groups={{group}},sudo shell=/bin/bash
# SSH
  - file: path=/home/{{user}} owner={{user}} group={{group}} mode=0774 state=directory
  - file: path=/home/{{user}}/.ssh owner={{user}} group={{group}} mode=0774 state=directory
  - lineinfile: dest=/root/.ssh/authorized_keys regexp="chroot" line="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC5wre4xEgakCPVpdIOHZx9HuxRfxcNZ7RVtAHaLvmQtmW1MMHmxSQDYIOxvVkMjvfnzIss2VAAOESNczRx7Mq7qRTZej4FTp7ZrFzUtOHLyhtUOebd9c1839qlXVk34EvbzFvi8ZWKMYYvBmrlNZxXAo7Q0FnNiUlK2Bx4D1inqFpE+E0y5AFFfBEgWNiF03aRCiPrGZN49Kq9hkpgVsI5bE6CNvdtO9ZTu7oNXQ6SQmRshXsZ5ydzfvBWxNE6qzZrj6NnimNwJd7bIsvDk/LB/QZJrVBd+0TzOjRusAVCH2liB2UJB5Sgl7ZVOk6gEyTZphWSvrV0luI4a4uOFpTp chroot@chroot"
  - command: cp -r /root/.ssh/ /home/{{user}}/
  - file: path=/home/{{user}}/.ssh/authorized_keys owner={{user}} group={{group}} mode=0600 state=file
  - file: path=/home/{{user}}/.ssh/id_rsa owner={{user}} group={{group}} mode=0600 state=file
  - file: path=/home/{{user}}/.ssh/id_rsa.pub owner={{user}} group={{group}} mode=0644 state=file
  - copy: dest=/home/{{user}}/.Xauthority content="" owner={{user}} group={{group}} mode=0600
  - name: ensure app apt dependencies are installed
    action: apt pkg={{item}}
    with_items:
      - git
      - wget
      - man-db
      - vim
      - tmux 
      - unzip
      #Eclipse deps
      - libgtk2.0-0
      - libxtst6
      #Android DT
      - telnet
# JDK 6.0 installed
#  - get_url: url=http://download.oracle.com/otn/java/jdk/6u45-b06/jdk-6u45-linux-i586.bin dest=/root
#  - command: sh /root/jdk-6u45-linux-i586.bin
  - command: >
      wget --no-cookies --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2Ftechnetwork%2Fjava%2Fjavase%2Fdownloads%2Fjdk6-downloads-1637591.html;" http://download.oracle.com/otn-pub/java/jdk/6u45-b06/jdk-6u45-linux-i586.bin -O /root/jdk6.bin creates=/root/jdk6.bin
  - file: path=/root/jdk6.bin  mode=0700 state=file
  - file: path=/usr/lib/jvm state=directory
  - command: /root/jdk6.bin chdir=/usr/lib/jvm creates=/usr/lib/jvm/jdk1.6.0_45
  - command: update-alternatives --install "/usr/bin/java" "java" "/usr/lib/jvm/jdk1.6.0_45/bin/java" 1
  - command: update-alternatives --install "/usr/bin/javac" "javac" "/usr/lib/jvm/jdk1.6.0_45/bin/javac" 1
  - command: update-alternatives --install "/usr/bin/javaws" "javaws" "/usr/lib/jvm/jdk1.6.0_45/bin/javaws" 1

- hosts: 127.0.0.1
  user: padawan
  vars:
    user: padawan
  tasks:
  - file: path=/home/{{user}}/src/ state=directory
  - name: clone coursera-android
    command: git clone https://github.com/aporter/coursera-android.git /home/{{user}}/src/coursera-android creates=/home/{{user}}/src/coursera-android
    
  - file: path=/home/{{user}}/zip/ state=directory
  - file: path=/home/{{user}}/unzip/ state=directory
  - file: path=/home/{{user}}/applications/ state=directory
  
# Android Development Toolkit (with eclipse)
  - get_url: url=http://dl.google.com/android/adt/adt-bundle-linux-x86-20131030.zip  dest=/home/{{user}}/zip/
  - command: unzip /home/{{user}}/zip/adt-bundle-linux-x86-20131030.zip chdir=/home/{{user}}/applications/ creates=/home/{{user}}/applications/adt-bundle-linux-x86-20131030
  
#Android studio
  - get_url: url=http://dl.google.com/android/studio/install/0.4.2/android-studio-bundle-133.970939-linux.tgz  dest=/home/{{user}}/zip/
  - command: tar zxvf /home/{{user}}/zip/android-studio-bundle-133.970939-linux.tgz chdir=/home/{{user}}/applications/ creates=/home/{{user}}/applications/android-studio
  
#Assignments  week 1  
  - get_url: url=https://d396qusza40orc.cloudfront.net/android%2FLabs%2FDevelopmentEnvironment%2FDevelopmentEnvironment.zip  dest=/home/{{user}}/zip/
  - command: unzip /home/{{user}}/zip/android%2FLabs%2FDevelopmentEnvironment%2FDevelopmentEnvironment.zip chdir=/home/{{user}}/src creates=/home/{{user}}/src/DevelopmentEnvironment
#Assignments  week 2
  - get_url: url=https://d396qusza40orc.cloudfront.net/android%2FLabs%2FTheActivityClass%2FTheActivityClass.zip dest=/home/{{user}}/zip/
  - command: unzip /home/{{user}}/zip/android%2FLabs%2FTheActivityClass%2FTheActivityClass.zip chdir=/home/{{user}}/src/ creates=/home/{{user}}/src/TheActivityClass
  - get_url: url=https://d396qusza40orc.cloudfront.net/android%2FLabs%2FTheActivityClass%2FActivityLabTest-v2.zip dest=/home/{{user}}/zip
  - command: unzip /home/{{user}}/zip/android%2FLabs%2FTheActivityClass%2FActivityLabTest-v2.zip chdir=/home/{{user}}/src/TheActivityClass/SourceFiles/TestCases creates=/home/{{user}}/src/TheActivityClass/SourceFiles/TestCases/ActivityLabTest/
#Assignments  week 3
  - get_url: url=https://d396qusza40orc.cloudfront.net/android%2FLabs%2FIntents%2FIntents.zip dest=/home/{{user}}/zip/
  - command: unzip /home/{{user}}/zip/android%2FLabs%2FIntents%2FIntents.zip chdir=/home/{{user}}/unzip/ creates=/home/{{user}}/unzip/Intents
  - command: cp -R /home/{{user}}/unzip/Intents /home/{{user}}/src/W3-Intents creates=/home/{{user}}/unzip/W3-Intents
  
  - get_url: url=https://d396qusza40orc.cloudfront.net/android%2FLabs%2FPermissions%2FPermissions.zip dest=/home/{{user}}/zip/
  - command: unzip /home/{{user}}/zip/android%2FLabs%2FPermissions%2FPermissions.zip chdir=/home/{{user}}/unzip/ creates=/home/{{user}}/unzip/Permissions
  - command: cp -R /home/{{user}}/unzip/Permissions /home/{{user}}/src/W3-Permissions creates=/home/{{user}}/unzip/W3-Permissions

  - get_url: url=https://d396qusza40orc.cloudfront.net/android%2FLabs%2FTheFragmentClass%2FFragments.zip dest=/home/{{user}}/zip/
  - command: unzip /home/{{user}}/zip/android%2FLabs%2FTheFragmentClass%2FFragments.zip chdir=/home/{{user}}/unzip/ creates=/home/{{user}}/unzip/Fragments
  - command: cp -R /home/{{user}}/unzip/Fragments /home/{{user}}/src/W3-Fragments creates=/home/{{user}}/unzip/W3-Fragments
#Assignments week 4 
  - get_url: url=https://d396qusza40orc.cloudfront.net/android%2FLabs%2FUserInterface%2FUserInterface.zip dest=/home/{{user}}/zip/
  - command: unzip /home/{{user}}/zip/android%2FLabs%2FUserInterface%2FUserInterface.zip chdir=/home/{{user}}/unzip/ creates=/home/{{user}}/unzip/UserInterface
  - command: cp -R /home/{{user}}/unzip/UserInterface /home/{{user}}/src/W4-UserInterface creates=/home/{{user}}/unzip/W4-UserInterface
  
