---
- hosts: 127.0.0.1
  vars:
    user: padawan
    group: mbs
  user: root
  tasks:
  - apt: upgrade=dist
  - apt: pkg=xauth state=installed
#We allow X11 forwarding
  - copy: dest=/root/.Xauthority content="" owner=root group=root mode=0600
  - user: name={{user}} password={{user}} createhome=yes groups={{group}},sudo shell=/bin/bash
  - name: ensure app apt dependencies are installed
    action: apt pkg={{item}}
    with_items:
      - git
      - wget
      - man-db
      - vim
      - tmux 
      - unzip

- hosts: 127.0.0.1
  user: padawan
  vars:
    user: padawan
  tasks:
  - file: path=/home/{{user}}/src/ state=directory
  - name: clone coursera-android
    command: git clone https://github.com/aporter/coursera-android.git /home/{{user}}/padawan/src
    
  - file: path=/home/{{user}}/zip/ state=directory
  - get_url: url=https://d396qusza40orc.cloudfront.net/android%2FLabs%2FDevelopmentEnvironment%2FDevelopmentEnvironment.zip  dest=/home/{{user}}/zip/
  - file: path=/home/{{user}}/applications/ state=directory
  - command: unzip android%2FLabs%2FDevelopmentEnvironment%2FDevelopmentEnvironment.zip chdir=/home/{{user}}/applications/ creates=/home/{{user}}/applications/devenv
  